services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roomifyDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    networks:
      - roomify_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  roomify_network:
    driver: bridge
    external: true
