spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/roomifyDB
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
